### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by JackLeEmmerdeur** [zekroTJA/yuri2#8]
Did not find a working soundboard runnable on linux, so yours is a last resort and it sounds really promising and impressive regarding the sourcecode.

What I've done:
- Installed go. Version is 1.7.4 which seems a little dated.
- Set GOPATH and GOROOT environment vars for go. 
- Put the project in $GOPATH/src

When entering make in project folder I get: 

<pre>
<code>
package main
        imports github.com/zekroTJA/yuri2/internal/database/sqlite: use of internal package not allowed
package main
	imports github.com/zekroTJA/yuri2/internal/inits: use of internal package not allowed
package main
	imports github.com/zekroTJA/yuri2/internal/logger: use of internal package not allowed
package main
	imports github.com/zekroTJA/yuri2/internal/static: use of internal package not allowed
</code>
</pre>

Is this a known phenomenon in the go land and maybe erridicated in a later version?

Thanks.

**Comment by zekroTJA** [comment]
Hey, I am really happy you like the project. :)

Are you sure you cloned yuri's sources into your set GOPATH source directory which is `${GOPATH}/src/github.com/zekroTJA/yuri2`?

I've reproduced the cloning and making steps on my Manjaro VM real quick where I've gone through the following steps:

```
$ mkdir -p src/github.com/zekroTJA/yuri2
$ export GOPATH=${PWD}
$ cd src/github.com/zekroTJA/yuri2
$ git clone https://github.com/zekroTJA/yuri2.git .
$ make
```

And the result was a clean build.

Little note I need to take here: The Makefile is actually kind of outdated because after the front end rework, it is necessary to build the front end files and moving them next to the binary for execution:

```
$ cd web
$ npm install
$ npm run build --prod
$ cd ..
$ mkdir bin/web
$ cp -r web/dist/ bin/web/
```

Also, I need to say, that I can not ensure that the build will be successful on Go version 1.7.x because I have started developing this project on Go 1.11.x and I will also consider switching from dep to go mod as dependency management for this project which will be only available for later versions of Go.

I hope this was helpful, at least a bit. :)

**Comment by JackLeEmmerdeur** [comment]
On the short glimpse into your code, it seemed to me more clean and concise than that of my current project. More I cannot say, but that there seems to have been poured a lot of work into it. The fact it's opensourced and I will run the server myself helps in monitoring the server for secret messages to some asian state ;-)
If it works, I'll definitely will support this project in some form. 

So I tried your proposed way but sadly no luck.
Previously I had the git-clone located in: `${GOPATH}/src/yuri2`. 
I moved it accordingly to: `${GOPATH}/src/github.com/zekroTJA/yuri2`.

My ${GOPATH} is: `/home/USER/projects/go`, 
It contains the directories `bin` (with a dep-executable in it) and `pkg/dep/sources` (with lot of github repos).

My go binary seems to be working, but I still got the same import errors. 

The whole output is:

<pre>
<code>
fatal: No names found, cannot describe anything.
dep ensure -v
fatal: No names found, cannot describe anything.
go build  \
	-v -o /home/USER/Documents/Projects/go/src/github.com/zektroTJA/yuri2/bin/yuri -ldflags "\
		-X github.com/zekroTJA/yuri2/static.AppVersion= \
		-X github.com/zekroTJA/yuri2/static.AppCommit=127f391dd709183ed0b7bac56d7b0442352c410a \
		-X github.com/zekroTJA/yuri2/static.Release=TRUE" \
	/home/USER/Documents/Projects/go/src/github.com/zektroTJA/yuri2/cmd/yuri/*.go
package main
	imports github.com/zekroTJA/yuri2/internal/database/sqlite: use of internal package not allowed
package main
	imports github.com/zekroTJA/yuri2/internal/inits: use of internal package not allowed
package main
	imports github.com/zekroTJA/yuri2/internal/logger: use of internal package not allowed
package main
	imports github.com/zekroTJA/yuri2/internal/static: use of internal package not allowed
Makefile:59:  the Rule for target „/home/USER/Documents/Projects/go/src/github.com/zektroTJA/yuri2/bin/yuri“ „all-recursive“ failed make: *** [/home/USER/Documents/Projects/go/src/github.com/zektroTJA/yuri2/bin/yuri] Fehler 1
</code>
</pre>

I'm not in a hurry, so if you investigate, you don't need to rush as I'm crunching myself, and won't have much time atm to tinker with discord. 

But thx for your attention anyway.

**Comment by zekroTJA** [comment]
Okay, I've tested the build another times on Debian Buster using Go version 1.7.4.  

I created the build flow inside a Dockerfile to have a clean environment for testing. Below, you can see the Dockerfile with all steps listed.

```Dockerfile
FROM debian:buster

ARG GO_VERSION="1.7.4"

# Install nessecary packages
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y curl git build-essential

# Install Golang 1.7.4 and dep
WORKDIR /root
RUN curl -Lo go.tgz \
        https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go.tgz \
    && chmod +x /usr/local/go/bin/* \
    && curl -Lo /usr/bin/dep \
        https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64 \
    && chmod +x /usr/bin/dep

# Create user and switch to it
RUN useradd tester --no-log-init -m -s /bin/bash
USER tester
WORKDIR /home/tester

# Create and define GOPATH and add $GOPATH/bin and
# GO compiler toolchain directory to PATH
ENV GOPATH "/home/tester/go"
ENV PATH "${GOPATH}/bin:/usr/local/go/bin:${PATH}"
RUN mkdir -p go

# Clone yuri2 into gopath and make it
RUN git clone https://github.com/zekroTJA/yuri2 \
        ./go/src/github.com/zekroTJA/yuri2 --branch master --depth 10 \
    && cd ./go/src/github.com/zekroTJA/yuri2 \
    && make \
    && ls -lisah ./bin
```

First of all, I got no errors of the type of `use of internal package not allowed`. I guess you have some packages in your gopath from erlier installation tries which may cause problems matching the right packages for the go compiler. Maybe you should try to clean up the whole go path (or use another directory), if this is possible.

But I've noticed another problem when compiling with go version 1.4.x while running the test:
```
# github.com/zekroTJA/yuri2/vendor/github.com/zekroTJA/gavalink
vendor/github.com/zekroTJA/gavalink/lavalink.go:96: undefined: sort.SliceStable
```
The thing is, that the method `sort.SliceStable` does not exist in this version so the nessecary package `gavalink` can not be compiled in this version.

So, you should consider using a later version of go. I've tested the same Dockerfile using go version `1.13.4` and everything compiled successfully.
```Dockerfile
ARG GO_VERSION="1.7.4"
```

**Comment by zekroTJA** [comment]
Okay cool, I'am really happy the problem is resolved.

Actually, because I have migrated all my services on my VPS into a Docker Compose environment and because I have written a lot of Dockerfiles before for my projects, projects of others or general server applications like Minecraft Spigot servers, I am verry convinient writing Docker images, so it did not took that much time. I can really suggest Docker not only as runtime service but also as testing environment for stuff like that.

Im marking this issue as `closed` because the origin problem is resolved.

Thanks for using Yuri and always feel free to submit issues if you notice bugs or if you have a cool idea. :)
